on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    # Para usar a ação privada desse repositório, é preciso fazer checkout do repositório
    - name: Checkout
      uses: actions/checkout@v1
    - uses: ./ # Usa uma ação no diretório raiz
    - name: Hello world action step
      id: hello
      uses: jhpego/docker_action@master
      with:
        who-to-greet: 'Jorge Pego3'
    # Use a saída da etapa 'hello'
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
